apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "gogs-pv" 
spec:
  capacity:
    storage: "5Gi" 
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  awsElasticBlockStore: 
    fsType: "ext4" 
    volumeID: "vol-57901787"

